# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: cluster-issuerq
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: gkibriaiu@email.com
#     privateKeySecretRef:
#       name: letsencrypt-cluster-issuer-key
#     solvers:
#     - http01:
#        ingress:
#          class: istio
# ---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cd-dev
  namespace: istio-system
spec:
  dnsNames:
    - cd-dev.eeko.ai
  secretName: cd-dev
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
