apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eeko-ai
  namespace: istio-system
spec:
  dnsNames:
    - eeko.ai
  secretName: eeko-ai
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
