---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuerq
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gkibriaiu@email.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
       ingress:
         class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-dev
  namespace: istio-system
spec:
  dnsNames:
    - admin-dev.eeko.ai
  secretName: admin-dev
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
