apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-dashboard-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
        number: 80
        name: http
        protocol: HTTP
    hosts:
        - app-dev.eeko.ai
    tls:
        httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
     - app-dev.eeko.ai
    tls:
      mode: SIMPLE
      credentialName: app-dev
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-dashboard-virtualservice
  namespace: istio-system
spec:
  hosts:
    - app-dev.eeko.ai
  gateways:
   - app-dashboard-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: frontend.default.svc.cluster.local
        port:
          number: 80
#---
# DestinationRule definition
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: kubernetes-dashboard
#   namespace: istio-system
# spec:
#   host: kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
#   trafficPolicy:
#     tls:
#       mode: SIMPLE
#       credentialName: registry-dev
# ---
# apiVersion: install.istio.io/v1alpha1
# kind: IstioOperator
# metadata:
#   name: example-istiocontrolplane
#   namespace: istio-system
# spec:
#   components:
#     ingressGateways:
#     - name: istio-ingressgateway
#       enabled: true
#       k8s:
#         env:
#         - name: ISTIO_META_USER_SDS
#           value: "true"
#         - name: SDS_ENABLED
#           value: "true"
