apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: registry-dashboard-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
     - registry-dev.eeko.ai
    tls:
      mode: SIMPLE
      credentialName: registry-dev
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registry-dashboard-virtualservice
  namespace: istio-system
spec:
  hosts:
    - registry-dev.eeko.ai
  gateways:
   - registry-dashboard-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: harbor-core.default.svc.cluster.local
        port:
          number: 80
#---
# DestinationRule definition
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: kubernetes-dashboard
#   namespace: istio-system
# spec:
#   host: kubernetes-dashboard.kubernetes-dashboard.svc.cluster.local
#   trafficPolicy:
#     tls:
#       mode: SIMPLE
#       credentialName: registry-dev
# ---
# apiVersion: install.istio.io/v1alpha1
# kind: IstioOperator
# metadata:
#   name: example-istiocontrolplane
#   namespace: istio-system
# spec:
#   components:
#     ingressGateways:
#     - name: istio-ingressgateway
#       enabled: true
#       k8s:
#         env:
#         - name: ISTIO_META_USER_SDS
#           value: "true"
#         - name: SDS_ENABLED
#           value: "true"
