apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: eeko-ai-dashboard-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
        number: 80
        name: http
        protocol: HTTP
    hosts:
        - eeko.ai
    tls:
        httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
     - eeko.ai
    tls:
      mode: SIMPLE
      credentialName: eeko-ai
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eeko-ai-dashboard-virtualservice
  namespace: istio-system
spec:
  hosts:
    - eeko.ai
  gateways:
   - eeko-ai-dashboard-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: frontend.default.svc.cluster.local
        port:
          number: 80
