apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: default
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-stable
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: stable
  template:
    metadata:
      labels:
        app: my-app
        version: stable
    spec:
      containers:
        - name: my-app
          image: 10.105.100.13:5000/canary-test/my-app:stable
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-canary
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: canary
  template:
    metadata:
      labels:
        app: my-app
        version: canary
    spec:
      containers:
        - name: my-app
          image: 10.105.100.13:5000/canary-test/my-app:canary
          ports:
            - containerPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cannary-dashboard-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - bdris-canary.gov.bd

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-app
  namespace: istio-system
spec:
  hosts:
    - bdris-canary.gov.bd
  gateways:
    - cannary-dashboard-gateway
  http:
    - route:
        - destination:
            host: my-app.default.svc.cluster.local
            subset: stable
          weight: 90
        - destination:
            host: my-app.default.svc.cluster.local
            subset: canary
          weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-app
  namespace: istio-system
spec:
  host: my-app.default.svc.cluster.local
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary